apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: radix-log-api
  title: Radix log API
  description: "API to access historical logs for Radix applications"
  annotations:
    github.com/project-slug: equinor/radix-log-api
    equinor.com/entity-markdown-readme-url: https://github.com/equinor/radix-log-api/blob/main/README.md
spec:
  type: openapi
  lifecycle: production
  owner: omnia-radix
  system: Radix
  definition:
    $text: "./docs/swagger.yaml"
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radix-log-api
  title: Radix log API
  description: "FastAPI backend for Radix log api"
  tags:
    - backend
    - api
  annotations:
    github.com/project-slug: equinor/radix-vulnerability-scanner-api
spec:
  type: service
  lifecycle: production
  owner: omnia-radix
  system: Radix
  providesApis:
    - radix-log-api
