apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-log-api
spec:
  environments:
    - name: qa
      build:
        from: main
    - name: prod
      build:
        from: release
  components:
    - name: server
      ports:
        - name: http
          port: 8000
      publicPort: http
      variables:
        AZURE_TENANT_ID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
        RADIX_LOG_API_PORT: "8000"
        RADIX_LOG_API_ISSUER: "https://sts.windows.net/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/"
        RADIX_LOG_API_AUDIENCE: "6dae42f8-4368-4678-94ff-3960e28e3630"
        RADIX_LOG_API_WORKSPACE_ID: "TBA"
      secrets:
        - "AZURE_CLIENT_ID"
        - "AZURE_CLIENT_SECRET"
      resources:
        requests:
          cpu: 100m
          memory: 200M
        limits:
          cpu: 500m
          memory: 1G
      environmentConfig:
        - environment: prod
          replicas: 2
      
