// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/controllers/interface.go
//
// Generated by this command:
//
//	mockgen -source ./api/controllers/interface.go -destination ./api/controllers/mock_controller.go -package controllers
//

// Package controllers is a generated GoMock package.
package controllers

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Endpoints mocks base method.
func (m *MockController) Endpoints() []Endpoint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Endpoints")
	ret0, _ := ret[0].([]Endpoint)
	return ret0
}

// Endpoints indicates an expected call of Endpoints.
func (mr *MockControllerMockRecorder) Endpoints() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Endpoints", reflect.TypeOf((*MockController)(nil).Endpoints))
}
