basePath: /api/v1
info:
  contact: {}
paths:
  /applications/{appName}/environments/{envName}/components/{componentName}:
    get:
      parameters:
      - description: Application Name
        in: path
        name: appName
        required: true
        type: string
      - description: Environment Name
        in: path
        name: envName
        required: true
        type: string
      - description: Component Name
        in: path
        name: componentName
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get inventory (pods and their containers) for a component
      tags:
      - Inventory
  /applications/{appName}/environments/{envName}/components/{componentName}/logs:
    get:
      parameters:
      - description: Application Name
        in: path
        name: appName
        required: true
        type: string
      - description: Environment Name
        in: path
        name: envName
        required: true
        type: string
      - description: Component Name
        in: path
        name: componentName
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - ApiKeyAuth: []
      summary: Get log for a component
      tags:
      - Logs
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: Bearer is currently not supported by go-swag. Use "Bearer <JWT>"
      in value.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
